config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'about' => 'welcome#about'
  
  root 'welcome#index'
  
  resources :users, only: [:show]
  
  resources :tasks, only: [:create, :index, :destroy] do
    put :complete
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  
  def time_left
    "this his eeasf"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :tasks
    
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
  def after_sign_in_path_for(resource)
    tasks_path
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    # t.string   "name"
    # t.integer  "user_id"
    # t.datetime "created_at"
    # t.datetime "updated_at"
    # t.datetime "expires_at"
    # t.boolean  "completed",  default: false
  
  before_action :authenticate_user!
  
  def create
    @task = current_user.tasks.build(task_params)
    @task.expires_at = Time.now + 7.days
    
    if @task.save
      flash[:notice] = "Task was created successfully"
    else
      flash[:error] = "Error creating task. Please try again."
    end
        
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @task = current_user.tasks.find(params[:id])
    
    if @task.destroy
      redirect_to tasks_path, notice: "Task was successfully deleted"
    else
      flash[:error] = "There was an error deleting your task"
      redirect_to @tasks_path
    end

  end
  
  def index
    @inactive_tasks = current_user.tasks.where("expires_at <= ? OR completed = ?", Time.now, true)
    @tasks = current_user.tasks.where("expires_at >= ?", Time.now).where(completed: false)
    @task = current_user.tasks
  end
  
  def complete
    @task = current_user.tasks.find(params[:task_id])
    if @task.completed
      @task.update_attribute(:completed, false)
      @task.save!
      # redirect_to tasks_path
    else
      @task.update_attribute(:completed, true)
      @task.save!
      # redirect_to tasks_path
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  private
  def task_params
    params.require(:task).permit(:name, :completed, :id, :expires_at)
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @task = @user.tasks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EdBlocitoff</title>
  <meta name="viewpoint" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="container">
    <nav class="navbar navbar-inverse navbar">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "EdBlocitoff", root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li style="color: #FFFFFF; margin:1em .5em .3em 1em; font-size: 1em"><%= "Hello #{current_user.name || current_user.email}!" %></li>
              <li><%= link_to "My Tasks", tasks_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>  
    </div>
  </div>  
  

  <%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for Task.new, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Tell us what you need to do.' %>
  </div>
    <%= f.submit "Create", class: 'btn btn-success', remote: true %>
<% end %>

app/views/tasks/_task.html.erb
    <tr <%= "id=task-#{t.id}" %>>
      <td><%= t.name %></td>
      <td><%= distance_of_time_in_words_to_now(t.expires_at) %></td>
      <% if t.completed %>
        <td><%= link_to "", task_complete_path(t), method: :put, class: 'glyphicon glyphicon-paperclip', remote: true %></td>
      <% else %>
        <td><%= link_to "", task_complete_path(t), method: :put, class: 'glyphicon glyphicon-ok', remote: true %></td>
      <% end %>
    </tr>

app/views/tasks/_tasks.html.erb
<tbody>
<% @tasks.each do |t| %>
    <tr>
      <td><%= t.name %></td>
      <td><%= distance_of_time_in_words_to_now(t.expires_at) %></td>
      <% if t.completed %>
      <td id="js-complete"><%= link_to "", task_complete_path(t), method: :put, class: 'glyphicon glyphicon-paperclip', remote: true %></td>
      <% else %>
      <td><%= link_to "", task_complete_path(t), method: :put, class: 'glyphicon glyphicon-ok' %></td>
      <% end %>
    </tr>
<% end %>  
</tbody>

app/views/tasks/complete.js.erb
$('#task-' +<%= @task.id %>).hide();

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/create.js.erb
<% if @task.save %>
  $('#js-tasks').append("<%= escape_javascript(render partial: 'tasks/task', locals: {t: @task}) %>");
<% else %>
  $('#new-task').html("<%= escape_javascript(render partial: 'form', locals: {task: @new_task}) %>");
<% end %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">My Tasks</div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Do It</th>
        <th>Days Left</th>
        <th>Done</th>
      </tr>
    </thead>
    <%= render partial: 'tasks', locals: {tasks: @tasks, task: @task} %>
  </table>
  <div class="col-md-3"></div>
  <div class="col-md-6" id="new-task">
    <%= render partial: 'form', locals: {task: @new_task} %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/welcome/about.html.erb
<div class="container">
<div class="jumbotron">
  <h1>EdBlocitoff</h1>
  <p>Self-destructing to-do-list that gets stuff done.</p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Do What You Gotta Do</h2>
    <p>Create Reminders of things you want to accomplish in the next 7 days.</p>
  </div>
  <div class="col-md-4">
    <h2>Self Destruction</h2>
    <p>Tasks that are not completed within 7 days are obliterated. BAM!</p>
  </div>
  <div class="col-md-4">
    <h2>Clock is Tickin'</h2>
    <p>Count down to the destruction of your tasks.</p>
  </div>
</div>
</div>

app/views/welcome/index.html.erb
<div class="container">
<div class="jumbotron">
  <h1 class="text-center">EdBlocitoff</h1>
  <p class="text-center">Self-destructing to-do-list that gets stuff done.</p>
  <% if !current_user %>
  <div class="text-center">
    <%= link_to "Sign Up Now!", new_user_registration_path, class: 'h3 btn btn-success text-center jumbo-btn' %>
  </div>
  <% end %>
  
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Do What You Gotta Do</h2>
    <p>Create Reminders of things you want to accomplish in the next 7 days.</p>
  </div>
  <div class="col-md-4">
    <h2>Self Destruction</h2>
    <p>Tasks that are not completed within 7 days are obliterated. BAM!</p>
  </div>
  <div class="col-md-4">
    <h2>Clock is Tickin'</h2>
    <p>Count down to the destruction of your tasks.</p>
  </div>
</div>
</div>